---
# Readarr Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: htpc
    run: readarr
  name: readarr
  namespace: htpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htpc
      run: readarr
  template:
    metadata:
      labels:
        app: htpc
        run: readarr
    spec:
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: lscr.io/linuxserver/readarr:nightly-0.4.5.2688-ls355
        name: readarr
        ports:
        - containerPort: 8787
          name: webui
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: readarr
        - mountPath: /books
          name: htpc-home
          subPath: media/books
        - mountPath: /downloads
          name: htpc-home
          subPath: downloads
      securityContext:
        fsGroup: 1000
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
