apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
  - name: linuxserver/jackett
    newTag: v0.21.2258-ls356
  - name: linuxserver/sonarr
    newTag: 4.0.3.1413-ls233
  - name: linuxserver/radarr
    newTag: 5.3.6.8612-ls211
  - name: linuxserver/bazarr
    newTag: v1.4.2-ls244
  - name: linuxserver/transmission
    newTag: 4.0.5-r0-ls228
  - name: emby/embyserver
    newTag: 4.9.0.12
  - name: linuxserver/ombi
    newTag: v4.43.5-ls186
  - name: linuxserver/jellyfin
    newTag: 10.10.3ubu2404-ls46
  - name: linuxserver/readarr
    newTag: nightly-0.4.5.2688-ls355
