apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v0.12.0-rc3

namespace: argocd

resources:
- namespace.yaml
- application.yaml
- ingress.yaml

patchesStrategicMerge:
- argo-server_patch.yaml
