apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    name: webui
  selector:
    run: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jellyfin
  template:
    metadata:
      labels:
        run: jellyfin
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: jellyfin
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: BASE_URL
          value: "/jellyfin"
        image: linuxserver/jellyfin
        name: jellyfin
        ports:
        - containerPort: 3579
          name: webui
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: jellyfin
